services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geeks-castle-api
    environment:
      PORT: 8080
      GOOGLE_APPLICATION_CREDENTIALS: /app/.keys/key.json
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID}
      PUBSUB_USER_CREATED_TOPIC: ${PUBSUB_USER_CREATED_TOPIC}
      PUBSUB_USER_CREATED_SUBSCRIPTION: ${PUBSUB_USER_CREATED_SUBSCRIPTION}
    ports:
      - '8080:8080'
    volumes:
      - ./.keys:/app/.keys:ro
    restart: unless-stopped
